name: Performance
version: '${project.version}'
main: me.the_ktc.performance.Main
api-version: 1.18
load: STARTUP
authors: [ The_KTC ]
description: A plugin for my Minecraft-Server
commands:
  performance:
    description: Ein Performance-modus!
  roleplay:
    description: Abhängig vom Input
  ktc:
    description: Healp!