name: Performance
version: '${project.version}'
main: me.the_ktc.performance.Main
api-version: 1.18
load: STARTUP
authors: [ The_KTC ]
description: A plugin to stop chrome and firefox
commands:
  performance:
    description: Ein Performance-modus!