name: Taskkill
version: '${project.version}'
main: the_ktc.taskkill.Taskkill
api-version: '1.20'
load: STARTUP
authors: [ The_KTC ]
description: "A plugin to kill processes"
commands:
  taskkill:
    description: "Ein Performance-modus!"
    usage: "ยง4Wrong usage: /taskkill <name of listed task to kill>"