name: Taskkill
version: '1.0-Snapshot'
main: the_ktc.taskkill.Taskkill
api-version: '1.20'
load: STARTUP
authors: [ The_KTC ]
description: "A plugin to kill processes"
commands:
  taskkill:
    description: "Ein Performance-modus!"
    usage: "ยง4Wrong usage: /taskkill <name of listed task to kill>"
    permission: "taskkill.use"
    children:
      '*':
        description: "Kills the specified task"
        usage: "/taskkill <taskname>"
        permission: "taskkill.use"